config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :donors, :controllers => { :omniauth_callbacks => "donors/omniauth_callbacks" }

  resources :messages

  resources :organizations

  resources :donations

  resources :needs

  resources :donors

  resources :users

  root 'needs#show', id: 1

  get 'pages/terms'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :need
  belongs_to :donor
  has_many :sent_messages
  has_many :donors, :through => :sent_messages

  accepts_nested_attributes_for :sent_messages, reject_if: proc { |attributes| attributes['donor_id'].to_s.to_i <= 0 }

  after_save :send_email

  def sent_to
    self.sent_messages.where('sent_at IS NOT NULL').collect {|sent| sent.donor.name}
  end

  def send_email
    self.sent_messages.where('sent_at IS NULL').each do |sent_message|
      next unless sent_message.donor.present?
      begin
        AdminMailer.message_email(self, sent_message.donor).deliver
        sent_message.update_attribute(:sent_at, Time.now)
      rescue
      end
    end
    return true
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    @need = Need.first
    @need.donors.each do |donor|
      @message.sent_messages.build(donor: donor)
    end
  end

  # GET /messages/1/edit
  def edit
    @need = @message.need
    @need.donors.each do |donor|
      @message.sent_messages.build(donor_id: donor.id)
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        @need = @message.need
        @message.sent_messages = @message.sent_messages.reject {|message| message.donor.blank?}

        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:need_id, :subject, :body, :sent_at, :donor_id, :sent_messages_attributes => [:donor_id])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :need_id, :value => Need.first.id %>
  <%= f.hidden_field :donor_id, :value => current_donor.id %>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %><br>

    <%= f.text_area :body, :class => "redactor", :rows => 40, :cols => 120  %>
  </div>

  <div class='field'>
    <%= f.fields_for(:sent_messages) do |sent_fields| %>
      <div class='check_box'>
        <%= sent_fields.check_box :donor_id, {disabled: !!sent_fields.object.sent_at}, sent_fields.object.donor_id %>
        <%= sent_fields.label :donor_id, sent_fields.object.donor.name %>
        <%= sent_fields.label :donor_id, sent_fields.object.donor.email %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Send', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>


<% @messages.each do |message| %>
  <%= message.body.html_safe %>
  Sent To: <%= message.sent_to.join(', ') %><br />
  <%= link_to "Show", message %>
  <%= link_to 'Edit / Resend', edit_message_path(message) %>
  <hr></hr>
<% end %>

<%= link_to 'New Message', new_message_path, class: 'btn btn-large btn-primary' %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<h1> Status Update for <%= @message.need.title %></h1>

<%= @message.body.html_safe %>