config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :donors, :controllers => { :omniauth_callbacks => "donors/omniauth_callbacks" }

  resources :messages

  resources :organizations

  resources :donations

  resources :needs

  resources :donors

  resources :users

  root 'needs#show', id: 1

  get 'pages/terms'
end

app/models/need.rb
class Need < ActiveRecord::Base
  has_many :donations
  has_many :donors, :through => :donations
  belongs_to :organization
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :amount_requested, numericality: { greater_than: 0 }

  def percent_complete
    (self.amount_donated / self.amount_requested.to_f) * 100
  end

end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_action :set_need, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin, only: [:index, :edit, :update, :destroy, :new, :create]

  # GET /needs
  # GET /needs.json
  def index
    @needs = Need.all
  end

  # GET /needs/1
  # GET /needs/1.json
  def show
    @donation = @need.donations.build
  end

  # GET /needs/new
  def new
    @need = Need.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create
    @need = Need.new(need_params)

    respond_to do |format|
      if @need.save
        format.html { redirect_to @need, notice: 'Need was successfully created.' }
        format.json { render :show, status: :created, location: @need }
      else
        format.html { render :new }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    respond_to do |format|
      if @need.update(need_params)
        format.html { redirect_to @need, notice: 'Need was successfully updated.' }
        format.json { render :show, status: :ok, location: @need }
      else
        format.html { render :edit }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to needs_url, notice: 'Need was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_need
      @need = Need.friendly.find(params[:id])
    end

    def need_params
      params.require(:need).permit(:title, :posted_at, :description, :amount_requested, :image)
    end
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/needs/_form.html.erb
<%= form_for(@need, :html => { :multipart => true }) do |f| %>
  <% if @need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>

      <ul>
      <% @need.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :posted_at %><br>
    <%= f.datetime_select :posted_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'wysihtml5' %>
  </div>
  <div class="field">
    <%= f.label :amount_requested %><br>
    <%= f.text_field :amount_requested %>
  </div>
  <%= f.file_field :image %>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/needs/edit.html.erb
<h1>Editing Need</h1>

<%= render 'form' %>

<%= link_to 'Show', @need %> |
<%= link_to 'Back', needs_path %>

app/views/needs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Needs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Posted at</th>
      <th>Description</th>
      <th>Amount requested</th>
      <th>Amount donated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @needs.each do |need| %>
      <tr>
        <td><%= need.title %></td>
        <td><%= need.posted_at %></td>
        <td><%= need.description %></td>
        <td><%= need.amount_requested %></td>
        <td><%= need.amount_donated %></td>
        <td><%= link_to 'Show', need %></td>
        <td><%= link_to 'Edit', edit_need_path(need) %></td>
        <td><%= link_to 'Destroy', need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Need', new_need_path %>

app/views/needs/new.html.erb
<h1>New Need</h1>

<%= render 'form' %>

<%= link_to 'Back', needs_path %>

app/views/needs/show.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class='col-md-4'>
        <div>
          <%= image_tag @need.image.url(:medium), :class => 'img-responsive' %>
          <!-- Go to www.addthis.com/dashboard to customize your tools -->
          <div class="addthis_sharing_toolbox"></div>
        </div>

      </div>

      <div class="first_row">
        <div class="col-md-4">
          <h3>
            <%= @need.title %>
          </h3>
        </div>
        <div class="col-md-4">
          <p class='posted_date'>
            <strong>Posted:</strong>
            <%= @need.posted_at.to_s(:long) %>
          </p>
        </div>
      </div>
      <div class="col-md-8">
        <p>
          <strong>Description:</strong>
          <%= @need.description.html_safe %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Amount requested:</strong>
          <%= number_to_currency @need.amount_requested %>
        </p>
      </div>
      <div class="col-md-4">
        <div class="progress">
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: <%= @need.percent_complete %>%;">
            <%= number_to_currency @need.amount_donated %>
          </div>
        </div>
        <p>
          <%= number_to_currency @need.amount_donated %> funded to-date<br>
          <%= number_to_currency (@need.amount_requested - @need.amount_donated) %> still needed
        </p>
      </div>
      <div class="col-md-8">
        <%= form_for(@donation, :url => new_donation_path, :method => :get) do |f| %>
        <% if @donation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

          <ul>
            <% @donation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class='row'>
          <div class='col-md-2 col-md-offset-6'>
            <div class="field">
              <%= f.select :amount, amount_list, {}, {:class => 'easyui-combobox'} %>
            </div>
          </div>
          <div class='col-md-2'>
            <%= f.hidden_field :need_id %>
            <div class="actions">
              <%= f.submit 'Donate', :class => 'btn btn-success btn-lg' %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div id='donor-images'>
      <% @need.donors.uniq.in_groups_of(6) do |group| %>
        <div class='row'>
          <% group.each do |donor| %>
            <% next unless donor %>
            <div class='col-md-2 donor-image'>
              <%= image_tag donor.image_url(:medium), :class => 'img-responsive' %>
              <br />
              <%= donor.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class='col-md-2 col-md-offset-8'>
      <% if current_donor && current_donor.is_admin? %>
        <%= link_to 'Edit Need', edit_need_path(@need), class: 'btn btn-info' %>
      <% end %>
    </div>

  </div>
</div>