config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :donors, :controllers => { :omniauth_callbacks => "donors/omniauth_callbacks" }

  resources :messages

  resources :organizations

  resources :donations

  resources :needs

  resources :donors

  resources :users

  root 'needs#show', id: 1

  get 'pages/terms'
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :need
  belongs_to :donor
  validates :amount, numericality: { greater_than: 0 }

  after_create :update_need_total

  def update_need_total
    self.need.amount_donated += self.amount
    self.need.save
  end

  def amount=(value)
    value.to_s.gsub!('$', '')
    super(value)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_donor!
  before_action :ensure_admin, only: [:index, :edit, :update, :destroy, :show]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new(donation_params)
    @client_token = Braintree::ClientToken.generate
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @result = Braintree::Transaction.sale(
        :amount => params[:donation][:amount].gsub('$', ''),
        :payment_method_nonce => params[:payment_method_nonce],
        :options => {
          :submit_for_settlement => true
        }
      )
    @donation = Donation.new(donation_params)
    raise @result.errors.inspect unless @result.success?
    respond_to do |format|
      if @result.success? && @donation.save
        if current_donor
          current_donor.braintree_last_4               = @result.transaction.credit_card_details.last_4
          current_donor.braintree_payment_method_token = @result.transaction.credit_card_details.token
          current_donor.save
        end

        format.html { redirect_to @donation.need, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:amount, :need_id, :donor_id, :number, :cvv, :month, :year, :payment_method_nonce)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class='col-md-8'>
      <div id="dropin"></div>
    </div>
  </div>
  <div class='row'>
    <div class="col-md-6">
      <%= f.select :amount, amount_list(@donation.amount.to_i), {selected: number_to_currency(@donation.amount.to_i, :precision => 0)}, {:class => 'easyui-combobox'} %>
    </div>
    <div class="col-md-2">
      <%= f.submit "Submit Donatation", :class => 'btn btn-primary' %>
    </div>
  </div>

  <%= f.hidden_field :need_id %>
  <%= f.hidden_field :donor_id, :value => current_donor.id %>
<% end %>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

<script>
  braintree.setup(
    // Replace this with a client token from your server
    '<%= @client_token %>',
    'dropin', {
      container: 'dropin'
    }
  );
</script>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Donations</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Need</th>
      <th>Donor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.need_id %></td>
        <td><%= donation.donor_id %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<div class='row'>
  <div class='col-md-11 col-md-offset-1'>
    <h1>New Donation</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/donations/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Need:</strong>
  <%= @donation.need_id %>
</p>

<p>
  <strong>Donor:</strong>
  <%= @donation.donor_id %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>