config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :donors, :controllers => { :omniauth_callbacks => "donors/omniauth_callbacks" }

  resources :messages

  resources :organizations

  resources :donations

  resources :needs

  resources :donors

  resources :users

  root 'needs#show', id: 1

  get 'pages/terms'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connect</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header class="container-fluid">
      <div class='row vertical-align'>
        <div class='col-md-4 col-md-offset-8'>
          <div class='pull-right'>
            <% if user_signed_in? %>
              <% if current_user.has_role? :admin %>
                <%= link_to messages_path do %>
                  <span><i class='glyphicon glyphicon-envelope'></i></span> Send Message
                <% end %>
              <% end %>
              |
              <%= link_to 'Update Profile', edit_user_path(current_user) %>
              |
              <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>

            <% elsif donor_signed_in? %>
              |
              <%= link_to 'Update Profile', edit_donor_path(current_donor) %>
              |
              <%= link_to 'Sign Out', destroy_donor_session_path, :method => :delete %>
              <%= image_tag current_donor.image_url, :width => '20px' %>
            <% else %>
              <%= link_to 'Donor Sign In', new_donor_session_path %>
              |
              <%= link_to 'User Sign In', new_user_session_path %>
            <% end %>
          </div>
        </div>
      </div>
      <div class='row vertical-align'>
        <div class='col-md-9'>
          <%= link_to root_path do %>
            <% if current_organization %>
              <%= image_tag current_organization.image.url, class: 'img-responsive' %>
            <% else %>
              <%= image_tag 'c2n-logo.png' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </div>

  <footer id='footer'>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 col-md-offset-4">
          &copy; 2014 - <%= Time.now.year %> Connect2Need
        </div>
        <div class="col-md-2">
          <a href="/pages/terms">Terms of Use</a>
        </div>
      </div>
    </div>
  </footer>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5010ab745b4bafa6" async="async"></script>
</body>
</html>